export default {
  products: [
    {
      _id: "5f3e8f70f64997350444149a",
      name: "Siyah Kuşaklı Gömlek Elbise",
      category: "Elbise",
      image: "/images/img1.jpg",
      price: 100,
      brand: " Bershka",
      rating: 4.5,
      numReviews: 10,
      countInStock: 10,
      description: "15 gün içinde ücretsiz iade."
    },
    {
      _id: "5f3e8f7ef64997350444149b",
      name: "US Polo Assn Beyaz Gömlek",
      category: "Gömlek",
      image: "/images/img2.jpg",
      price: 50,
      brand: "US Polo Assn",
      rating: 4.2,
      numReviews: 5,
      countInStock: 10,
    },
    {
      _id: "5f3e8feaf64997350444149c",
      name: "Kadın Siyah Motorcu Tarz Fermuarlı Ceket",
      category: "Pants",
      image: "/images/img3.jpg",
      price: 329.99,
      brand: "Mango",
      rating: 4.5,
      numReviews: 8,
      countInStock: 10,
    },
    {
      _id: "5f3ea66bf64997350444149d",
      name: "Siyah Kadın Yarı Zincir Askılı Kilit Detaylı Omuz Çantası",
      category: "Çanta",
      image: "/images/img4.jpg",
      price: 70,
      brand: " Bagzone",
      rating: 4.5,
      numReviews: 8,
      countInStock: 6,
    },
    {
      _id: "5f3ea66bf64997350444149e",
      name: "Unisex Polarize Güneş Gözlüğü",
      category: "Gözlük",
      image: "/images/img5.jpg",
      price: 70,
      brand: "Aqua Di Polo",
      rating: 4.5,
      numReviews: 8,
      countInStock: 6,
    },
    {
      _id: "5f3ea66cf64997350444149f",
      name: "Sıyah Kadın Klasik Topuklu Ayakkabı",
      category: "Ayakkabı",
      image: "/images/img6.jpg",
      price: 80,
      brand: "Yaya by Hotiç",
      rating: 4.5,
      numReviews: 8,
      countInStock: 6,
    }
  ],
};
